### ISSUE TITLE
Unable to run `flickrsync` on OS X 10.12.5

### ISSUE THREAD

**Issue by dalanmiller** [danchal/flickrsync#3]
I've confirmed I have all the requirements installed:

```
$ brew install freetype imagemagick
Warning: freetype 2.8 is already installed
Warning: imagemagick 7.0.7-1 is already installed
```

Error:

```
$ flickrsync
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wand/api.py", line 180, in <module>
    libraries = load_library()
  File "/usr/local/lib/python3.6/site-packages/wand/api.py", line 135, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flickrsync", line 3, in <module>
    from flickrsync.flickrsync import main
  File "/usr/local/lib/python3.6/site-packages/flickrsync/flickrsync.py", line 12, in <module>
    from flickrsync import local
  File "/usr/local/lib/python3.6/site-packages/flickrsync/local.py", line 7, in <module>
    from wand.image import Image
  File "/usr/local/lib/python3.6/site-packages/wand/image.py", line 20, in <module>
    from .api import MagickPixelPacket, libc, libmagick, library
  File "/usr/local/lib/python3.6/site-packages/wand/api.py", line 206, in <module>
    'Try to install:\n  ' + msg)
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  brew install freetype imagemagick
```

**Comment by danchal** [comment]
For OSX, you may need to export the imagemagick path?
`$ export MAGICK_HOME=/opt/local`
[How to use or install MagickWand on Mac OS X?](https://stackoverflow.com/questions/24803747/how-to-use-or-install-magickwand-on-mac-os-x)

**Comment by dalanmiller** [comment]
I think this was actually an issue with Python 3.6, installing on Python
2.7 everything seemed to be fine.

**Comment by danchal** [comment]
I have only developed this using Python3, not sure that it will work with Python2?

**Comment by FMassin** [comment]
Try:
brew install freetype imagemagick@6                                                          
export MAGICK_HOME=/usr/local/opt/imagemagick@6/
